# Generated by Django 5.2.6 on 2025-10-20 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiesgoCrediticio',
            fields=[
                ('idRiesgo', models.AutoField(primary_key=True, serialize=False)),
                ('riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], max_length=20)),
                ('razon', models.TextField()),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgos', to='clientes.cliente')),
            ],
        ),
    ]
