# Generated by Django 5.2.6 on 2025-11-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_crediticio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riesgocrediticio',
            options={'ordering': ['-fecha_prediccion'], 'verbose_name': 'Riesgo Crediticio', 'verbose_name_plural': 'Riesgos Crediticios'},
        ),
        migrations.AlterModelTable(
            name='riesgocrediticio',
            table='riesgo_crediticio',
        ),
        migrations.CreateModel(
            name='BotActivity',
            fields=[
                ('idActividad', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('recordatorio', 'Recordatorio enviado'), ('consulta', 'Consulta atendida'), ('reporte', 'Reporte generado'), ('calculo', 'Cálculo realizado'), ('otro', 'Otra acción')], default='otro', max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Actividad del Bot',
                'verbose_name_plural': 'Actividades del Bot',
                'db_table': 'bot_activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='bot_activit_timesta_44a202_idx'), models.Index(fields=['action_type', 'timestamp'], name='bot_activit_action__164406_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatInteraction',
            fields=[
                ('idInteraccion', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, default='anonymous', max_length=100)),
                ('sender', models.CharField(choices=[('user', 'Usuario'), ('bot', 'Bot')], max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Interacción de Chat',
                'verbose_name_plural': 'Interacciones de Chat',
                'db_table': 'chat_interactions',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['user_id', 'timestamp'], name='chat_intera_user_id_a860c0_idx')],
            },
        ),
    ]
